### PR TITLE
Switch to cmake as build system

### PR DESCRIPTION
**Pull request by morxa**
This implements #34

### CODE REVIEW

**Comment by WuBingzheng** [comment]
I get this at Ubuntu 16.04:

    $ cmake ..
    -- Checking for one of the modules 'IMPORTED_TARGET;libdw'
    -- Checking for one of the modules 'IMPORTED_TARGET;libdwarf'
    CMake Warning at CMakeLists.txt:51 (message):
      Could not find libdw or libdwarf.  File name and line number will not be
      shown in backtrace.


    -- Configuring done
    CMake Error at CMakeLists.txt:12 (add_executable):
      Target "memleax" links to target "PkgConfig::LIBUNWIND" but the target was
      not found.  Perhaps a find_package( call is missing for an IMPORTED
      target, or an ALIAS target is missing?


    CMake Error at CMakeLists.txt:12 (add_executable):
      Target "memleax" links to target "PkgConfig::LIBELF" but the target was not
      found.  Perhaps a find_package( call is missing for an IMPORTED target, or
      an ALIAS target is missing?


    -- Generating done
    -- Build files have been written to: /home/wub/tmp/memleax-cmake))

**Comment by morxa** [comment]
Thanks for testing! I only have a Fedora system for testing, so I couldn't find these problems. I'll have a look and I'll check if I can find an Ubuntu system for testing.

**Comment by morxa** [comment]
So it turns out the PkgConfig features I'm using were added with cmake 3.6, and Ubuntu 16.04 still uses cmake 3.5.

**Comment by morxa** [comment]
Also, I forgot to push the machine type detection. Working on a fix for both.

**Comment by morxa** [comment]
This should fix both issues.

Note that if your Ubuntu system still complains about missing libelf: This is actually an Ubuntu bug in pkgconfig, see the related [Debian discussion](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885071). Installing `zlib1g-dev`, `libbz2-dev`, and `liblzma-dev` should fix it.

**Comment by WuBingzheng** [comment]
This works after I install these 3 libraries.
I will do more test these days.

Thanks

**Comment by WuBingzheng** [comment]
Sorry that reply so late.

I try cmake at FreeBSD 10.4, and get this error:

    -- Checking for one of the modules 'libelf'
    CMake Error at /usr/local/share/cmake/Modules/FindPkgConfig.cmake:640 (message):
      None of the required 'libelf' found
    Call Stack (most recent call first):
      CMakeLists.txt:65 (pkg_search_module)


    -- Checking for one of the modules 'libdw'
    -- Checking for one of the modules 'libdwarf'
    CMake Warning at CMakeLists.txt:79 (message):
      Could not find libdw or libdwarf.  File name and line number will not be
      shown in backtrace.


    -- Configuring incomplete, errors occurred!
    See also "/home/wub/memleax/build/CMakeFiles/CMakeOutput.log".

There are libelf and libdwarf. And if I use the original `configure` to generate Makefile, I can build memleax. However `cmake` reports libelf and libdwarf missing.

Are your familiar with FreeBSD?

**Comment by morxa** [comment]
Not really... Is pkg-config installed on the system? If so, does it find the packages? In particular, what's the output of:

```
$ pkg-config --exists libelf ; echo $?
$ pkg-config --exists libdw ; echo $?
$ pkg-config --exists libdwarf ; echo $?
```

**Comment by WuBingzheng** [comment]
pkg-config finds libelf after I install it by pkg. There was a libelf before already. I do not know the reason.

pkg-config still can not find libdwarf even I have installed it by pkg.

Another problem is that, since cmake has run successfully (skipping libdwarf) and I get a Makefile, when I run `make`, there is error again:

    % make
    [  9%] Linking C executable memleax
    /usr/bin/ld: cannot find -lunwind-x86_64
    cc: error: linker command failed with exit code 1 (use -v to see invocation)

Maybe the reason is that libunwind is in /usr/local/lib. 
I add `link_directories(/usr/local/lib/)` in CMakeLists.txt before `target_link_libraries(memleax PRIVATE unwind-x86_64)`, but it still does not work.

---
I am busy these days so I have no time to learn cmake.
I think your pull request is ok for Fedora, if you want to package memleax for Fedora.
But I can not merge it before test it in FreeBSD.

**Comment by morxa** [comment]
OK, I'll see if I can get access to a FreeBSD VM, but if pkg-config cannot find the lib, there is some issue with the system. We can always try to find the lib manually, but I would do this only if it's really necessary.

Maybe the search path of pkg-config simply doesn't include `/usr/local`. Do you have pkg-config files in `/usr/local`? (I assume `/usr/local/lib/pkgconfig` or similar)

**Comment by WuBingzheng** [comment]
`link_directories` should add lib path, but I do not why it fails.

There are some pkgconf libs in /usr/local/lib/ : 

    wub@:~ % ls /usr/local/lib/libpkgconf*
    /usr/local/lib/libpkgconf.a
    /usr/local/lib/libpkgconf.so
    /usr/local/lib/libpkgconf.so.3
    /usr/local/lib/libpkgconf.so.3.0.0

**Comment by morxa** [comment]
`link_directories` manually specifies the directory used by the linker. This is what pkg-config is supposed to do. `link_directories` is not used by pkg-config.

Can you try setting `CMAKE_PREFIX_PATH` to `/usr/local`?
```
$ cmake -DCMAKE_PREFIX_PATH=/usr/local ..
```

**Comment by regan2** [comment]
I am still failing to find libdwarf on Fedora:
```
-- Checking for one of the modules 'libdw'
-- Checking for one of the modules 'libdwarf'
CMake Warning at CMakeLists.txt:79 (message):
  Could not find libdw or libdwarf.  File name and line number will not be
  shown in backtrace.
```
I have both libdwarf and libdwarf-devel installed with dnf.
pkg-config cannot find them because they don't seem to have .pc files at all. 
The following prints nothing:
`$ sudo find / -name "*.pc" | grep "dw"`

**Comment by morxa** [comment]
> I am still failing to find libdwarf on Fedora:
> 
> ```
> -- Checking for one of the modules 'libdw'
> -- Checking for one of the modules 'libdwarf'
> CMake Warning at CMakeLists.txt:79 (message):
>   Could not find libdw or libdwarf.  File name and line number will not be
>   shown in backtrace.
> ```
> 
> I have both libdwarf and libdwarf-devel installed with dnf.
> pkg-config cannot find them because they don't seem to have .pc files at all.
> The following prints nothing:
> `$ sudo find / -name "*.pc" | grep "dw"`

True, but on Fedora, you can just use libdw. You'll need to install `elfutils-devel`:
```
$ dnf repoquery --whatprovides 'pkgconfig(libdw)'
elfutils-devel-0:0.170-11.fc28.i686
elfutils-devel-0:0.170-11.fc28.x86_64
elfutils-devel-0:0.174-5.fc28.i686
elfutils-devel-0:0.174-5.fc28.x86_64
```

**Comment by regan2** [comment]
Thanks, `elfutils-devel` worked for me.

**Pull request merged**
