### PR TITLE
Replace hash data structure in ptr_backtrace.c with a list from list.h

### PR DESCRIPTION
**Pull request by jonesmz**
The use of a hash for key-lookup doesn't give us any time savings, given that the key is relatively small.

This patch does result in allocating space for each backtrace that we capture, but I'm skeptical that there'll be a considerable runtime difference.

### CODE REVIEW

**Comment by jonesmz** [comment]
I suppose that using the ARRAY() macro might be closer to the current way the datastructure works, but again I think it's a minimal difference.

**Comment by WuBingzheng** [comment]
There may be thousands entries, so I think hash is necessary.
By the way, what's the benefit of list?

**Comment by jonesmz** [comment]
The data being hashed is sizeof(void*), so hashing it and comparing the hash is basically more computational complexity than just comparing the data directly.

I'm re-writing memleax in C++ in my repository https://github.com/jonesmz/memleax/tree/cpp

Based on the way the data was used, I replaced this with an std::map in my code.

your list.h was the closest data structure to std::map.

Using array.h would also work.

**Comment by WuBingzheng** [comment]
I still think hash is necessary for search in thousands entries.
Add the complexity of API for hash and list is same, both are clear and simple.

**Pull request closed without merging**
