### PR TITLE
Use size_t for integral types that count a number of objects

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by WuBingzheng** [comment]
I use 'size_t' only for size.
I use 'int' for count, and 'long' for big count.
This is just personal preference.

**Comment by jonesmz** [comment]
At least use "unsigned int" and "unsigned long". It's not possible to have negative quantities.

**Comment by WuBingzheng** [comment]
There will be many places to be changed.
This code is very common:

    int i; 
    for (i =0; i < n; i++) { ... }

As you said, the `int i;` should be changed to `unsigned int i;`.

**Comment by jonesmz** [comment]
Yes, absolutely those should be changed.

One thing at a time is still better than nothing.

**Comment by WuBingzheng** [comment]
I remember that I read "use int if no particular reason" some where long ago.
Just now I search "should use unsigned int" on internet, and many people say to avoid using it.

Besides, there are some conventional usage in history, I think we should keep it if no particular reason. So the readers will not spend time on "why he write code like this?"

**Pull request closed without merging**
