### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by jonesmz**
Adds a clang-format configuration file, and runs it against the project.

Feel free to not merge 3b68ada, and to instead tweak the .clang-format file and apply your own format options.

### CODE REVIEW

**Comment by WuBingzheng** [comment]
I think this is about personal preference, but not about the project.

**Comment by jonesmz** [comment]
memleax coding style is inconsistent.

Clang format can help keep it consistent.

Please reconsider.

**Comment by WuBingzheng** [comment]
Would you like give some examples of inconsistent code?

**Comment by jonesmz** [comment]
You can see for yourself in the provided code changes.

Those were the options that I thought modified the code the least.

While the version of clang-format that I have isn't capable of reproducing the memleax code style identically, it comes pretty close.

SpaceBeforeParan is one that's applied inconsistantly
BreakBeforeBrace is another.
AlignVariableDeclarations
AlignVariableAssignments

Indendation, tab vs. space, number of tabs/spaces.


If you don't like the specific .clang-format options that I chose, feel free to modify to your liking. But having a coding style that can be enforced by a program is still superior to having to edit everything manually.

**Comment by WuBingzheng** [comment]
I do not understand the items very much. So I check the code changes.

- I add one space after `for` `while` keywords.
- I write `{` at the same line of `for` `while` `if` with a leading space, but a new line for functions.
- I align the member names in struct define, by tabs.
- I do not align the variables in functions. I think this is not conflict with the last one.
- I add 2 more tabs if break line.
- I use tab for indent. However I find that there are 2 functions with spaces!!!

  - One is `_ptr_access_reg()` under MLX_AARCH64. I write this functoin under my new RaspberryPi, and may had not setup the editor's environment correctly.
  - Another is `debug_line_search_dwdie()`. I can not find the reason.

I will correct the indent later. For others I think I do it good.

I keep the code style while writing code, but not format it later.
I have to admit that your format tool is useful because it dose find my wrong indent.
However I still think the tools should not be included in the project, while the tools should be at the coder's computer and works for his all projects.

**Pull request closed without merging**
